config/routes.rb
Bookboard::Application.routes.draw do

  resources :books,    only: [:create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'tags/:tag', to: 'users#show', as: :tag

  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
  validates :author,  presence: true
  validates :title,   presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books, dependent: :destroy
  before_save { email.downcase! }
  before_create :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:success] = "Book created!"
      redirect_to :back
    else
      @user  = current_user.reload
      render 'users/show'
    end
  end

  def destroy
    @book.destroy
    redirect_to current_user
  end

  private

    def book_params
      params.require(:book).permit(:title, :author)
    end

    def correct_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to user_path(current_user) if @book.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :destroy, :index]
  before_action :existing_user,  only: [:new, :create]
  before_action :correct_user,   only: [:edit, :update]
  before_action :manage_user,    only: :destroy
  before_action :admin_user,     only: :index
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Bookboard!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    if current_user?(@user)
      @book = current_user.books.build
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if current_user?(@user)
      @user.destroy
      flash[:success] = "Account deleted, thanks for trying Bookboard!"
    else # User is an admin
      User.find(params[:id]).destroy
      flash[:success] = "User destroyed."
    end
    redirect_to(root_url)
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
    end

    # Before filters

    def existing_user
      redirect_to(current_user) if signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def manage_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Bookboard"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/_book.html.erb
<li>
  <span class="title"><%= book.title %></span><br>
  by <span class="author"><%= book.author %></span>
  <% if current_user?(book.user) %>
    <%= link_to "delete", book, method: :delete,
                                data: { confirm: "You sure?" },
                                title: book.title %>
  <% end %>
  <p><%= raw book.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Made in NYC by Bob Gardner (2013)
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li>|</li>
            <li><%= link_to "Contact", contact_path %><li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "bookboard", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "My Books", current_user %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% if current_user.admin? %>
                  <li class="divider"></li>
                  <li><%= link_to "All users", users_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up!", signup_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all",
                               "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/shared/_book_form.html.erb
<%= form_for(@book) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <ul id="book_form">
    <%= f.text_field :title,  placeholder: "Title of book" %>
    <%= f.text_field :author, placeholder: "Author of book" %>
    <%= f.submit "Add book", class: "btn btn-primary" %>
  </ul>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(object.errors.count, "error") %>
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
    Bookboard's mission is to bring people together using the power of books.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    <%= mail_to("rgardner929@gmail.com", "Bob Gardner",
                                        { subject: "Bookboard" }) %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div id="help">
    <h1>Help</h1>
    <h3>Create an Account</h3>
    <p>Sample text</p>
    <h3>Adjust Privacy Settings</h3>
    <p>Sample text</p>
    <h3>Adding Friends</h3>
    <p>Sample text</p>
    <h3>Creating a Bookboard</h3>
    <p>Sample text</p>
    <h3>Why does voting sometimes make me include a message?</h3>
    <p>Sample text</p>
    <h3>Why can't I add a book to a friend's list</h3>
    <p>Sample text</p>
    <h3>What are those blanks in the book history?</h3>
    <p>Sample text</p>
    <h3>Close an Account</h3>
    <p>Sample text</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>
<div class="center hero-unit">
    <h1>Welcome to Bookboard</h1>
    <h2>The online community for sharing and comparing reading lists</h2>
    <%= link_to "Sign up now!", signup_path,
        class: "btn btn-large btn-primary" %>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    <section>
      <%= gravatar_for @user %>
      <%= link_to "change profile picture", "http://gravatar.com/emails",
                                         target: "_blank" %>
    </section>
    <h3>Privacy</h3>
    <h3>Download your data</h3>
    <h3>Delete Account</h3>
    <p>
      Deleting your account removes all of your bookboards. The urls to them
       will immediately be invalid and will redirect to the home page.
    </p>
    <%= link_to "Delete Account", @user, method: :delete,
                                         data: { confirm: "You sure?" },
                                          class: "btn btn-danger" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
            <%= render 'fields', f: f %>
            <%= f.submit "Create my account",
                         class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="span3">
        <section>
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section>
          <h3>Booklists</h3>
          <p>Nothing to see here yet...</p>
        </section>
    </aside>
    <div class="span9">
      <h3>Books (<%= @user.books.count %>)</h3>
      <%= render 'shared/book_form' if current_user?(@user) %>
      <% if @user.books.any? %>
        <ol class="books">
          <%= render @user.books %>
        </ol>
      <% end %>
    </div>
</div>